#!/bin/bash

while getopts "u:i:" opt; do
  case $opt in
    u)
      USER=$OPTARG
      ;;
    i)
      KEY=$OPTARG
      ;;
  esac
done

#echo $USER
#echo $KEY
scp -i $KEY dnsserver Makefile $USER@cs5700cdnproject.ccs.neu.edu:~
ssh -i $KEY $USER@cs5700cdnproject.ccs.neu.edu 'make dns'

while read line
do
    scp -i $KEY httpserver Makefile $USER@$line:~
    ssh -n -i $KEY $USER@$line 'make http'
done < serverlist.txt
