#!/bin/bash

#scp

while getopts ":u:i:" opt; do
  case $opt in
    u)
      USER=$OPTARG
      ;;
    i)
      KEY=$OPTARG
      ;;
  esac
done

echo $USER
echo $KEY

scp -i $KEY httpserver dnsserver Makefile $USER@ec2-52-90-80-45.compute-1.amazonaws.com:~
ssh $USER@ec2-52-90-80-45.compute-1.amazonaws.com 'make'
