#!/bin/bash

while getopts "u:i:n:p:o:" opt; do
  case $opt in
    u)
      USER=$OPTARG
      ;;
    i)
      KEY=$OPTARG
      ;;
  esac
done

scp -i $KEY dnsserver Makefile $USER@cs5700cdnproject.ccs.neu.edu:~
ssh -i $KEY $USER@cs5700cdnproject.ccs.neu.edu 'make dns'

while read line
do
    scp -r -i $KEY httpserver Makefile pre-cache.sh pre-cache.txt $USER@$line:~
    ssh -n -i $KEY $USER@$line './pre-cache.sh &' &
    ssh -n -i $KEY $USER@$line 'make http'
done < serverlist.txt
