#!/bin/bash

while getopts "u:i:n:p:o:" opt; do
  case $opt in
    u)
      USER=$OPTARG
      ;;
    i)
      KEY=$OPTARG
      ;;
    p)
      PORT=$OPTARG
      ;;
    n)
      NAME=$OPTARG
      ;;
    o)
      ORIGIN=$OPTARG
      ;;
  esac
done

ssh -i $KEY $USER@cs5700cdnproject.ccs.neu.edu "~/dnsserver -p \"$PORT\" -n \"$NAME\" &" 

while read line
do
    echo $line
    ssh -n -i $KEY $USER@$line "~/httpserver -p \"$PORT\" -o \"$ORIGIN\" & ~/scamper_server -p \"$PORT\" &" &
done < serverlist.txt
