#!/bin/bash

while getopts "u:i:n:p:o:" opt; do
  case $opt in
    u)
      USER=$OPTARG
      ;;
    i)
      KEY=$OPTARG
      ;;
    p)
      PORT=$OPTARG
      ;;
    n)
      NAME=$OPTARG
      ;;
    o)
      ORIGIN=$OPTARG
      ;;
  esac
done

ssh -i $KEY $USER@cs5700cdnproject.ccs.neu.edu "/usr/sbin/fuser -k $PORT/udp"

while read line
do
    echo $line
    ssh -n -i $KEY $USER@$line "fuser -k $PORT/tcp && fuser -k $PORT/udp"
    ssh -n -i $KEY $USER@$line "fuser -k 40029/tcp"

done < serverlist.txt
